### PR TITLE
adds ability to decrypt the message from the cli

### PR DESCRIPTION
**Pull request by logicminds**
* adds puppet node decrypt
  * previously there was no way to decrypt the message easily.
    This adds a cli fact for decrypting the value.

### CODE REVIEW

**Comment by logicminds** [comment]
These need some unit tests which I am not sure exactly how to add, but this adds capability to decrypt the given message.

**Comment by logicminds** [comment]
looks like you beat me to it.  @binford2k

**Comment by binford2k** [comment]
hahahahah, oh, this is funny.

**Comment by binford2k** [comment]
Same ideas even

**Pull request closed without merging**
